title: Kou Hang Hoi's Homepage
page-top-title: Kou Hang Hoi
top-section-bg-text: Computer Science
home-subtitle: Kou Hang Hoi&ensp;|&ensp;高珩栩
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
